# Generated by Django 5.2.1 on 2025-05-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planosexcel', '0002_rename_plano_planoexcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoexcel',
            name='hoja',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
